name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cinema-app
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache-dependency-path: cinema-app/package-lock.json
      - name: Install dependencies
        run: npm i
  backend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cinema-app
    needs: backend
    concurrency: heroku-deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: cinema-app
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: cinema-project-beadando
          heroku_email: boti.marcell@gmail.com
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cinema-client
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache-dependency-path: cinema-client/package-lock.json
      - name: Install dependencies
        run: npm i
  frontend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cinema-client
    needs: frontend
    concurrency: heroku-deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: cinema-client
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: cinema-client
          heroku_email: boti.marcell@gmail.com